name: CICD

on:
  workflow_dispatch:
    inputs:
      tf_workspace:
        description: 'Terraform Cloud Workspace'
        required: true
        default: 'mf-platform-app-demo'

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}      
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate GitHub CLI
      run: |        
        gh auth status

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

   
